version: "3"

volumes:
  kvsdatadev:

services:
  kvs:
    container_name: "kvs"
    image: "node:12"
    command: "npm run start:dev"
    working_dir: "/app"
    volumes:
      - ".:/app"
      - "kvsdatadev:/usr/local/etc/kvs/data/"
      - "./kvs-config.json:/usr/local/etc/kvs/kvs-config.json"
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:3-alpine"

